-- V2.15 precision pass: suppress high-confidence noise before it consumes validation time.
-- Adds P1/P2/P3 research priority without treating priority as proof of demand.

alter table public.research_leads
  add column if not exists research_priority text not null default 'p3',
  add column if not exists priority_reason text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='public.research_leads'::regclass
      and conname='research_leads_priority_check'
  ) then
    alter table public.research_leads
      add constraint research_leads_priority_check
      check (research_priority in ('p1','p2','p3'));
  end if;
end $$;

create index if not exists research_leads_priority_status_recent
  on public.research_leads(research_priority,status,created_at desc);

create or replace function public.radar_github_internal_issue(
  p_title text,
  p_body text,
  p_payload jsonb
)
returns boolean
language sql
immutable
set search_path=pg_catalog
as $$
  select
    lower(coalesce(p_payload->'user'->>'type',''))='bot'
    or lower(coalesce(p_body,'')) ~
      '(this was generated by ai during triage|generated from document-first|unit of work for one agent|dispatched to a subagent)'
    or (
      lower(coalesce(p_payload->>'author_association','')) in ('owner','member','collaborator')
      and (
        lower(coalesce(p_title,'')) ~
          '^(task:|ops-[0-9]+:|uc-[0-9]+:|\[devops\]|platform spike:|design:|[0-9]{4}-[0-9]{2}-[0-9]{2}[ ]*\|)'
        or lower(coalesce(p_body,'')) ~
          '(lane owns|must not touch|done when|planning document:|one discovery artifact:|parent issue:[ ]*#[0-9]+|subtask of #[0-9]+|blocked by #[0-9]+|definition of done for this issue|current checkpoint:|implementation repository:|status[ ]*\*\*proposed, not decided|nothing here should be implemented|owner has to choose between the options|bug-fixing sweep|found while fixing #[0-9]+|no mainstream client triggers|exploratory business roles and revenue models only|not a launch recommendation|not a .*validation plan|customer outreach.*not)'
        or exists (
          select 1
          from jsonb_array_elements(coalesce(p_payload->'labels','[]'::jsonb)) label
          where lower(coalesce(label->>'name','')) ~
            '(type:task|owner:agent|ready-for-agent|stage:(plan-approved|needs-spec)|^architecture$|(^|:)chore$|^internal$)'
        )
      )
    );
$$;

create or replace function public.radar_freelancer_low_value_task(
  p_title text,
  p_body text,
  p_payload jsonb
)
returns boolean
language sql
immutable
set search_path=pg_catalog
as $$
  with x as (
    select lower(concat_ws(' ',coalesce(p_title,''),coalesce(p_body,''))) txt,
           lower(coalesce(p_title,'')) title,
           length(coalesce(p_body,'')) body_len
  )
  select
    txt ~ '(data entry|copy typing|copy-typing|straightforward text data entry|manual transcription|typing job|pdf text extraction|extract(ing)? the text exactly|converted? into clean,? (error-free )?text)'
    or title ~ '(discord welcome bot|windows-based game automation)'
    or (
      body_len < 500
      and title ~ '(specialist|expert)'
      and txt ~ '(automation|crm|oracle|n8n|gohighlevel)'
    )
  from x;
$$;

create or replace function public.radar_stackoverflow_product_intent(
  p_title text,
  p_body text
)
returns boolean
language sql
immutable
set search_path=pg_catalog
as $$
  select lower(concat_ws(' ',coalesce(p_title,''),coalesce(p_body,''))) ~
    '(would pay|willing to pay|paid (tool|app|service)|pay for (a|an|this) (tool|app|service)|looking for (a|an|some) (paid )?(tool|app|service|alternative)|need (a|an) (commercial|hosted|paid) (tool|app|service)|subscription.{0,40}(looking|need|replace))';
$$;

-- Clean existing high-confidence false positives before the future-write trigger is installed.
update public.signals s
set is_actionable=false,
    evidence_role='market_context',
    money_signal_type='none',
    purchase_intent_score=least(coalesce(s.purchase_intent_score,1),1),
    extraction_version=case
      when position('+v215-internal-guard' in coalesce(s.extraction_version,''))=0
        then left(coalesce(s.extraction_version,'') || '+v215-internal-guard',120)
      else s.extraction_version end
from public.raw_items ri
join public.sources src on src.id=ri.source_id
where s.raw_item_id=ri.id
  and src.key='github'
  and s.is_actionable
  and public.radar_github_internal_issue(ri.title,ri.body,ri.raw_payload);

update public.signals s
set is_actionable=false,
    extraction_version=case
      when position('+v215-labor-guard' in coalesce(s.extraction_version,''))=0
        then left(coalesce(s.extraction_version,'') || '+v215-labor-guard',120)
      else s.extraction_version end
from public.raw_items ri
join public.sources src on src.id=ri.source_id
where s.raw_item_id=ri.id
  and src.key='freelancer'
  and s.is_actionable
  and public.radar_freelancer_low_value_task(ri.title,ri.body,ri.raw_payload);

update public.signals s
set is_actionable=false,
    evidence_role='market_context',
    money_signal_type='none',
    purchase_intent_score=least(coalesce(s.purchase_intent_score,1),1),
    extraction_version=case
      when position('+v215-so-intent-guard' in coalesce(s.extraction_version,''))=0
        then left(coalesce(s.extraction_version,'') || '+v215-so-intent-guard',120)
      else s.extraction_version end
from public.raw_items ri
join public.sources src on src.id=ri.source_id
where s.raw_item_id=ri.id
  and src.key='stackoverflow'
  and s.is_actionable
  and not public.radar_stackoverflow_product_intent(ri.title,ri.body);

create or replace function public.radar_precision_guard_signal()
returns trigger
language plpgsql
security invoker
set search_path=public,pg_catalog
as $$
declare
  r record;
begin
  select ri.title,ri.body,ri.raw_payload,src.key as source_key
    into r
  from public.raw_items ri
  join public.sources src on src.id=ri.source_id
  where ri.id=new.raw_item_id;

  if r.source_key='github'
     and public.radar_github_internal_issue(r.title,r.body,r.raw_payload) then
    new.is_actionable:=false;
    new.evidence_role:='market_context';
    new.money_signal_type:='none';
    new.purchase_intent_score:=least(coalesce(new.purchase_intent_score,1),1);
    if position('+v215-internal-guard' in coalesce(new.extraction_version,''))=0 then
      new.extraction_version:=left(coalesce(new.extraction_version,'') || '+v215-internal-guard',120);
    end if;
  elsif r.source_key='freelancer'
     and public.radar_freelancer_low_value_task(r.title,r.body,r.raw_payload) then
    new.is_actionable:=false;
    if position('+v215-labor-guard' in coalesce(new.extraction_version,''))=0 then
      new.extraction_version:=left(coalesce(new.extraction_version,'') || '+v215-labor-guard',120);
    end if;
  elsif r.source_key='stackoverflow'
     and not public.radar_stackoverflow_product_intent(r.title,r.body) then
    new.is_actionable:=false;
    new.evidence_role:='market_context';
    new.money_signal_type:='none';
    new.purchase_intent_score:=least(coalesce(new.purchase_intent_score,1),1);
    if position('+v215-so-intent-guard' in coalesce(new.extraction_version,''))=0 then
      new.extraction_version:=left(coalesce(new.extraction_version,'') || '+v215-so-intent-guard',120);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_radar_precision_guard_signal on public.signals;
create trigger trg_radar_precision_guard_signal
before insert or update of is_actionable,evidence_role,money_signal_type,purchase_intent_score
on public.signals
for each row execute function public.radar_precision_guard_signal();

create or replace function public.radar_research_priority_for_signal(p_signal_id uuid)
returns text
language sql
stable
security invoker
set search_path=public,pg_catalog
as $$
  with x as (
    select s.*,src.key source_key,ri.title,ri.body,ri.raw_payload,
           lower(concat_ws(' ',coalesce(ri.title,''),coalesce(ri.body,''),coalesce(s.problem,''))) txt
    from public.signals s
    join public.raw_items ri on ri.id=s.raw_item_id
    join public.sources src on src.id=s.source_id
    where s.id=p_signal_id
  )
  select case
    when not coalesce(is_actionable,false) then 'p3'

    when source_key='hackernews'
      and lower(coalesce(title,'')) ~
        '^(what tools do you wish existed|tell hn: looking for help|get feedback|ask hn: what are you building)'
      then 'p3'
    when source_key='hackernews'
      and (
        money_signal_type='purchase_request'
        or (
          coalesce(pain_score,0)>=7
          and coalesce(evidence_quality_score,0)>=8
          and txt ~ '(daily|weekly|monthly|hours|minutes|every time|each time|manual|manually|blocked|cost|pay|budget|[0-9]+[ ,]?(users|teams|clients|requests|tokens|hours))'
        )
      ) then 'p1'
    when source_key='hackernews' and evidence_role='problem_demand'
      and coalesce(pain_score,0)>=5 and coalesce(evidence_quality_score,0)>=6
      then 'p2'

    when source_key='amo_reviews' and evidence_role='problem_demand'
      and coalesce(pain_score,0)>=7 then 'p1'
    when source_key='amo_reviews' and evidence_role='problem_demand'
      and coalesce(pain_score,0)>=5 then 'p2'

    when source_key='freelancer'
      and public.radar_freelancer_low_value_task(title,body,raw_payload)
      then 'p3'
    when source_key='freelancer'
      and (
        lower(coalesce(title,'')) ~
          '(lead generation|roofing|crm .*build|crm setup|specialist|expert|development|game automation|discord .*bot|bookkeeping with custom reports)'
        or (
          txt ~ '(looking for|seeking|commissioning|i need|i want).{0,100}(developer|develop|create|build|application|app|platform|crm|bot|tool|mvp)'
          and txt !~ '(remind|follow.?up|supplier|vendor|product feed|supplier feed|any file that follows the same column structure|rule-driven|monthly close|reconcil|missing (documents?|items?|information))'
        )
      ) then 'p3'
    when source_key='freelancer'
      and coalesce(raw_payload->>'demand_class','')='repeatable_workflow'
      and txt ~ '(scheduled|remind|follow.?up|recurring|repeatable|batch|reconcil|supplier|vendor|product feed|supplier feed|outstanding|missing (documents?|items?|information)|any file that follows the same column structure|rule-driven|[0-9][0-9,]* (skus?|messages?|records?|rows?|clients?|vendors?|invoices?))'
      and txt !~ '(lead generation|roofing leads|game automation)'
      then 'p2'
    else 'p3'
  end
  from x;
$$;

-- Backfill priorities while preserving human promotion decisions.
update public.research_leads rl
set research_priority=case
      when rl.status='validate' then 'p1'
      when rl.status='research' then
        case when public.radar_research_priority_for_signal(rl.anchor_signal_id)='p3' then 'p2'
             else public.radar_research_priority_for_signal(rl.anchor_signal_id) end
      else public.radar_research_priority_for_signal(rl.anchor_signal_id)
    end,
    priority_reason=case
      when rl.status='validate' then 'Manual validation track: keep at the top until Build or Archive.'
      when rl.status='research' then 'Manually promoted to Research; worth active review but not validated demand.'
      when public.radar_research_priority_for_signal(rl.anchor_signal_id)='p1'
        then 'Strong explicit/quantified problem signal; review first.'
      when public.radar_research_priority_for_signal(rl.anchor_signal_id)='p2'
        then 'Specific product-shaped workflow worth manual review.'
      else 'Single, vague, generic-labor or custom-build signal; keep out of the active inbox.'
    end,
    updated_at=now();

update public.research_leads
set status='archived',
    decision_reason=coalesce(
      nullif(decision_reason,''),
      'V2.15 auto-triage: low-priority single/custom-service signal; no active validation slot.'
    ),
    priority_reason='Single, vague, generic-labor or custom-build signal; keep out of the active inbox.',
    reviewed_at=coalesce(reviewed_at,now()),
    updated_at=now()
where origin='auto' and status='new' and research_priority='p3';

create or replace function public.radar_research_lead_priority_guard()
returns trigger
language plpgsql
security invoker
set search_path=public,pg_catalog
as $$
declare
  v_priority text;
begin
  if new.status='validate' then
    v_priority:='p1';
    new.priority_reason:='Manual validation track: keep at the top until Build or Archive.';
  elsif new.status='research' then
    v_priority:=public.radar_research_priority_for_signal(new.anchor_signal_id);
    if v_priority='p3' then v_priority:='p2'; end if;
    new.priority_reason:='Manually promoted to Research; worth active review but not validated demand.';
  elsif new.origin='curated' and new.status<>'archived' then
    v_priority:='p2';
    new.priority_reason:='Manually curated source-backed lead.';
  else
    v_priority:=public.radar_research_priority_for_signal(new.anchor_signal_id);
    new.priority_reason:=case v_priority
      when 'p1' then 'Strong explicit/quantified problem signal; review first.'
      when 'p2' then 'Specific product-shaped workflow worth manual review.'
      else 'Single, vague, generic-labor or custom-build signal; keep out of the active inbox.'
    end;
  end if;

  new.research_priority:=v_priority;

  if new.origin='auto' and new.status='new' and v_priority='p3' then
    new.status:='archived';
    new.decision_reason:=coalesce(
      nullif(new.decision_reason,''),
      'V2.15 auto-triage: low-priority single/custom-service signal; no active validation slot.'
    );
    new.reviewed_at:=coalesce(new.reviewed_at,now());
  end if;

  return new;
end;
$$;

drop trigger if exists trg_research_lead_priority_guard on public.research_leads;
create trigger trg_research_lead_priority_guard
before insert or update of status,anchor_signal_id,origin
on public.research_leads
for each row execute function public.radar_research_lead_priority_guard();

revoke all on function public.radar_github_internal_issue(text,text,jsonb) from public,anon,authenticated;
revoke all on function public.radar_freelancer_low_value_task(text,text,jsonb) from public,anon,authenticated;
revoke all on function public.radar_stackoverflow_product_intent(text,text) from public,anon,authenticated;
revoke all on function public.radar_research_priority_for_signal(uuid) from public,anon,authenticated;
revoke all on function public.radar_precision_guard_signal() from public,anon,authenticated;
revoke all on function public.radar_research_lead_priority_guard() from public,anon,authenticated;

grant execute on function public.radar_github_internal_issue(text,text,jsonb) to service_role;
grant execute on function public.radar_freelancer_low_value_task(text,text,jsonb) to service_role;
grant execute on function public.radar_stackoverflow_product_intent(text,text) to service_role;
grant execute on function public.radar_research_priority_for_signal(uuid) to service_role;
grant execute on function public.radar_precision_guard_signal() to service_role;
grant execute on function public.radar_research_lead_priority_guard() to service_role;
